name: Build release

on:
  workflow_dispatch:

env:
  RELEASE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: amyu/setup-android@v2
        with:
          build-tools-version: '34.0.0'
          cmake-version: '3.22.1'
          ndk-version: '21.4.7075529'
          sdk-version: '34'

      - name: Set up keys
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE }}
        run: |
          mkdir -p "$KEYSTORE_PATH"
          echo $KEYSTORE_BASE64 | base64 -d > "$KEYSTORE_PATH"/release.keystore
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble release
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Assemble bundle
        run: ./gradlew bundleRelease

      - name: Upload Bundle
        uses: actions/upload-artifact@v1
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab